---
title: "Alphas"
author: "Elena Wall"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(broom)
library(cowplot)
library(ggplot2)
library(qiime2R)
library(tidyverse)
library(ggsignif)
library(rstatix)
library(ggpubr)
library(RColorBrewer)
library(ggpmisc)
library(viridis)

```

```{r}

#Load in 858 rarefied data
weightedUniAim858 <- read_qza("./DIET merged/core-metrics-ASV_fltrd_slva_mergedDIET-rared-858//weighted_unifrac_pcoa_results.qza")$data
unWeightUniAim858 <- read_qza("./DIET merged/core-metrics-ASV_fltrd_slva_mergedDIET-rared-858/unweighted_unifrac_pcoa_results.qza")$data
weightUniProp858 <- weightedUniAim858$ProportionExplained[1:2]
unweightUniProp858 <- unWeightUniAim858$ProportionExplained[1:2]

#turn them into tibbles and stuff
myWeightUniPcoa858 <- as_tibble(weightedUniAim858$Vectors)
myUnweightUniPcoa858 <- as_tibble(unWeightUniAim858$Vectors)

colnames(myWeightUniPcoa858)[1] <- '#SampleID'
colnames(myUnweightUniPcoa858)[1] <- '#SampleID'

mymeta <- read_tsv("./DIET merged/merged_metadata1.tsv")

mymeta %>% 
  mutate(day_post_inf = as.numeric(day_post_inf))%>% 
  filter(!is.na(day_post_inf), `#SampleID` != '2B_0506_9740', mouse_id != 9839) ->mymeta
 # na.omit() -> mymeta

# load diversity metrics
myShannon858 <- read_qza('./DIET merged/core-metrics-ASV_fltrd_slva_mergedDIET-rared-858/shannon_vector.qza')$data
myFaith858 <- read_qza('./DIET merged/core-metrics-ASV_fltrd_slva_mergedDIET-rared-858/evenness_vector.qza')$data
myEvenness858 <- read_qza('./DIET merged/core-metrics-ASV_fltrd_slva_mergedDIET-rared-858/faith_pd_vector.qza')$data

# turn them into tibbles and create a new column because
# tibbles don't have rownames!
myShannon858 <- as_tibble(myShannon858, rownames = '#SampleID')
myFaith858 <- as_tibble(myFaith858, rownames = '#SampleID')
myEvenness858 <- as_tibble(myEvenness858, rownames = '#SampleID')

#This is where I load in the Taxa data at genus level - obtained as a csv from the taxabar plot on qiime2
#Could also load in taxonomy.qza from qiime2
myTaxa858_lvl6 <- read_csv('./DIET merged/core-metrics-ASV_fltrd_slva_mergedDIET-rared-858/level-6_858.csv')
myTaxa858_lvl6 <- as_tibble(myTaxa858_lvl6)
colnames(myTaxa858_lvl6)[1] <- '#SampleID'

```

```{r}

#making a function just for myAlphas production

myAlphas_maker <- function(Taxa, Shannon, Evenness, Faith) {
  Taxa %>% 
  left_join(Shannon) %>% 
  left_join(Evenness) %>% 
  left_join(Faith) -> myAlphas

      return(myAlphas)
}

# making a function to create a tidy table with Merged/Joined and gathered data
data_merger_maker <- function(Taxa, Shannon, Evenness, Faith) {
  Taxa %>% 
  left_join(Shannon) %>% 
  left_join(Evenness) %>% 
  left_join(Faith) -> myAlphas

# Tidying
myAlphas %>% 
  select(`#SampleID`, diet, study , day_post_inf, mouse_id,
         shannon_entropy, faith_pd, pielou_evenness) ->lessAlphas
  
lessAlphas %>% gather(-`#SampleID`, -diet, -study , -day_post_inf, -mouse_id,
         key = 'Alpha', value = 'Value') -> tidyAlphas

      return(tidyAlphas)
}

```

```{r}
merged_858 <- data_merger_maker(myTaxa858_lvl6, myShannon858, myEvenness858, myFaith858)
   
merged_858 %>% 
 mutate(Alpha = case_when(Alpha == 'faith_pd' ~ "Faith's Phylogenetic\nDiversity",
                           Alpha == 'shannon_entropy' ~ "Shannon",
                           TRUE ~ "Evenness")) %>% 
  ggplot(aes(y = Value, x = day_post_inf)) +
    geom_jitter(height = 0, alpha = 0.3, width = 0.1, aes(color = diet)) +
    geom_smooth(aes( color = diet), se = F)+
    scale_color_viridis(option ="C", direction =-1,  discrete =TRUE)+
    facet_wrap(~Alpha, scales = 'free_y') +
    labs(x = "Days Post Infection", y = "Value",
       title = "Alpha Diversity Across Experimental Days",
       color = "Diet") +
    theme_bw(base_size = 18)+
    theme(legend.position="bottom")


```
Checking Evenness against top taxa

```{r}
myAlphas858 <- myAlphas_maker(myTaxa858_lvl6, myShannon858, myEvenness858, myFaith858)

#858 is my sampling depth

#narrowing down the taxa that I specifically look at for now
mySpecificTaxaTable_maker <- function(myAlphas) {
myAlphas %>% 
  select(matches("g__Lactobacillus|f__Tannerellaceae|f__Muribaculaceae|g__Akkermansia|g__Enterococcus|g__Parasutterella|f__Enterobacteriaceae|g__Bacteroides|f__Lachnospiraceae|g__Staphylococcus|g__Lachnoclostridium|g__Clostridioides"), `#SampleID`, diet, study , day_post_inf, mouse_id, shannon_entropy, faith_pd, pielou_evenness) -> mySpecificAlphas
      return(mySpecificAlphas)
}

#make 858 TaxaTables
mySpecificAlphas858<-mySpecificTaxaTable_maker(myAlphas858)

#make a function to attach PC1 and PC2 to TaxaTable

myPcoaAndTaxaTidy_maker <- function(myUniPcoA, mySpecificAlphas) {
myUniPcoA %>% 
  select(`#SampleID`, PC1, PC2) %>% 
  left_join(mySpecificAlphas) -> TaxaUniPcoa
  
  TaxaUniPcoa %>% 
  gather(-`#SampleID`, -diet, -study , -day_post_inf, -mouse_id, - PC1, -PC2, 
         -shannon_entropy,-faith_pd, -pielou_evenness, key = 'Taxa', value = 'Count') -> tidyTaxaUniPcoa

  tidyTaxaUniPcoa$Count <- as.numeric(tidyTaxaUniPcoa$Count)  
      return(tidyTaxaUniPcoa)
}
```

```{r} 
#need weightedUniPcoA and unweighted for non alpha analyses

weightTidyTaxaUniPcoa_858 <- myPcoaAndTaxaTidy_maker(myWeightUniPcoa858, mySpecificAlphas858)
unweightTidyTaxaUniPcoa_858 <- myPcoaAndTaxaTidy_maker(myUnweightUniPcoa858, mySpecificAlphas858)

```


```{r}
#Make functions for plots
myPcoaEvenness_plotter <- function(tidyTaxaUniPcoa, Title) {
  tidyTaxaUniPcoa %>% 
      ggplot(aes(x = day_post_inf, y = pielou_evenness)) +
      ggtitle(Title) +
      geom_jitter(height = 0, width = 0.1, alpha=0.3, aes(color = diet)) +
      geom_smooth(aes(color = diet), method = "loess",se = FALSE)+
      scale_fill_viridis(option ="C", direction = -1,  discrete =TRUE) +
      scale_color_viridis(option ="C", direction =-1,  discrete =TRUE)+
      theme_bw(base_size = 18) +
      scale_size_continuous(name="Evenness") +
      theme(legend.position="right")+
      ylab('Evenness')+
      xlab('Day Relative to Infection') -> evennessXdpi
        return(evennessXdpi)
}

#all the taxa plotted as facets - It's A LOT! DONT DO THIS UNLESS READY
myPcoaEvennessTaxa_plotter <- function(tidyTaxaUniPcoa, Title, SamplingDepth) {
tidyTaxaUniPcoa%>% 
  mutate(Taxa = str_replace_all(Taxa,".*f__", "")) %>% 
  ggplot(aes(x = day_post_inf, y =pielou_evenness, color = diet, size = ((Count/SamplingDepth)*100))) +
    ggtitle(Title) +
    geom_smooth(aes(color = diet), se = F)+
    geom_point(aes(fill = diet), pch = 21, alpha=0.3, color = 'black') +
    scale_fill_viridis(option ="C", direction = -1,  discrete =TRUE) +
    scale_color_viridis(option ="C",direction =-1,  discrete =TRUE)+
    facet_wrap(~Taxa, nrow = 3)+
    theme_bw(base_size = 18) +
    theme(axis.text.x = element_text(size = 12,
                                     vjust = 0.5),
          legend.position="bottom")+
    ylab('Evenness')+
    xlab('Day Relative to Infection') -> TaxaXevennessXdpi

    return(TaxaXevennessXdpi)
}

#use function for plots
#Weighted
weightedEvennessPlots_858 <- myPcoaEvenness_plotter(weightTidyTaxaUniPcoa_858, "Evenness Across Experiment")



print(weightedEvennessPlots_858)

```

```{r}

#WANT A FUNCTION WITH A STRING AS ARGUMENT?

myOneTaxa_maker <- function(tidyTaxaUniPcoa, OneTaxa) {
tidyTaxaUniPcoa %>% 
  filter(grepl(OneTaxa, Taxa)) %>% 
  mutate(GenSp = str_replace_all(Taxa,".*f__", " "))->tidyOneTaxa

class(tidyOneTaxa$Count)
tidyOneTaxa$Count <- as.numeric(tidyOneTaxa$Count)

      return(tidyOneTaxa)
}

```

```{r}
#just different ways of visualizing the data/ make functions later
OneAkker<- 'Akkermansia'

tidyAkkerTaxa858 <- myOneTaxa_maker(weightTidyTaxaUniPcoa_858, OneAkker)


tidyAkkerTaxa858%>% 
  ggplot(aes(x = day_post_inf, y = ((Count/858)*100))) +
    ggtitle("Akkermansia Relative Abundance Over Experiment") +
    geom_smooth(aes(color = diet), se = F)+
    geom_point(aes(fill = diet ),pch = 21, alpha=1, color = 'black') +
    scale_fill_viridis(option ="C", direction = -1,  discrete =TRUE) +
    scale_color_viridis(option ="C",direction =-1,  discrete =TRUE)+
    theme_bw(base_size = 18) +
    theme(legend.position="bottom")+
    ylab('Akkermansia Relative Abundance')+
    xlab('Day Relative to Infection')

tidyAkkerTaxa858%>% 
  ggplot(aes(x = day_post_inf, y =((Count/858)*100), color = diet, size = pielou_evenness)) +
    ggtitle("Akkermansia Relative Abundance and Evenness across Experiment") +
    geom_smooth(aes(color = diet), se = F)+
    geom_point(aes(fill = diet), pch = 21, alpha=0.3, color = 'black') +
    scale_fill_viridis(option ="C", direction = -1,  discrete =TRUE) +
    scale_color_viridis(option ="C", direction =-1,  discrete =TRUE)+
    theme_bw(base_size = 18) +
    scale_size_continuous(name="Evenness") +
    theme(legend.position="right")+
    labs(fill = 'Diet', color = 'Diet')+    
    ylab('Akkermansia Relative Abundance')+
    xlab('Days Post Infection')

tidyAkkerTaxa858%>% 
  ggplot(aes(x = day_post_inf, y =pielou_evenness, color = diet, size = ((Count/858)*100))) +
    ggtitle("Akkermansia Relative Abundance and Evenness across Experiment") +
    geom_smooth(aes(color = diet), se = F)+
    geom_point(aes(fill = diet), pch = 21, alpha=0.3, color = 'black') +
    scale_fill_viridis(option ="C", direction = -1,  discrete =TRUE) +
    scale_color_viridis(option ="C", direction =-1,  discrete =TRUE)+
    theme_bw(base_size = 18) +
    scale_size_continuous(name="Rel. Abund.") +
    theme(legend.position="right")+
    labs(fill = 'Diet')
```